### PR TITLE
Add link redirect into detail and edit - admin

### PR DESCRIPTION
**Pull request by hungbkdn**

### CODE REVIEW

**Comment by ghost** [comment]
This pull request cover for *redirect into list* or *redirect into list and edit*?

**Comment by hungbkdn** [comment]
I have update this title, please check it again
Thank you so much!

**Comment by ghost** [comment]
I just see the redirects to detail and edit page.

**Comment by hungbkdn** [comment]
It has a link in user page redirect into list order item, please check it again :smiley:

**Comment by hungbkdn** [comment]
Oh sorry, it also show method, i have updated title, please check it again!
Thank you so much

**Comment by ghost** [comment]
LGTM

**Pull request merged**
